# Generated by Django 4.2.11 on 2024-05-13 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edurep', '0004_is_extracted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdurepOAIPMH',
        ),
    ]
