# Generated by Django 4.2.15 on 2024-09-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_new_harvester'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS django_site CASCADE;',
        ),
    ]
