# Generated by Django 4.2.22 on 2025-06-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='users',
        ),
        migrations.RemoveField(
            model_name='queryranking',
            name='query',
        ),
        migrations.RemoveField(
            model_name='queryranking',
            name='user',
        ),
        migrations.DeleteModel(
            name='MatomoVisitsResource',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
        migrations.DeleteModel(
            name='QueryRanking',
        ),
    ]
