# Generated by Django 3.2.20 on 2023-08-04 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_harvestsource_repository'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonCartridge',
        ),
        migrations.DeleteModel(
            name='YouTubeDLResource',
        ),
    ]
