version: 2
updates:

  # Repo root dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for Harvester (Python)
  - package-ecosystem: "pip"
    directory: "/harvester"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Exclude Javascript dependencies for Harvester for the time being
  - package-ecosystem: "npm"
    directory: "/portal"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

  # Exclude search service dependencies
  - package-ecosystem: "pip"
    directory: "/service"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]
