# Generated by Django 4.2.21 on 2025-06-05 10:42

from django.db import migrations, models
import organizations.models.datatypes.containers


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_dataset_version_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='tasks',
            field=models.JSONField(blank=True, default=organizations.models.datatypes.containers.default_set_tasks),
        ),
    ]
