# Generated by Django 4.2.15 on 2024-09-19 15:22

import core.models.datatypes.dataset
import core.models.datatypes.document
import core.models.datatypes.set
import core.utils.decoders
import datagrowth.datatypes.documents.db.collection
import datetime
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import projects.models.datatypes.project


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_new_harvester'),
        ('search', '0002_multi_entity_index'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_harvested', models.BooleanField(default=False)),
                ('indexing', models.CharField(choices=[('no', 'No'), ('index_only', 'Index only'), ('index_and_promote', 'Index and promote')], default='no', max_length=50)),
            ],
            options={
                'verbose_name': 'project dataset',
                'verbose_name_plural': 'project datasets',
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('pending_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('is_index_promoted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, default=core.models.datatypes.dataset.version_default, max_length=50)),
                ('tasks', models.JSONField(blank=True, default=core.models.datatypes.dataset.default_dataset_version_tasks)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.dataset')),
            ],
            options={
                'verbose_name': 'project dataset version',
                'verbose_name_plural': 'project dataset version',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('delete_policy', models.CharField(blank=True, choices=[('no', 'No'), ('persistent', 'Persistent'), ('transient', 'Transient')], max_length=50, null=True)),
                ('tasks', models.JSONField(blank=True, default=core.models.datatypes.set.default_set_tasks)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='projects.datasetversion')),
            ],
            options={
                'verbose_name': 'project set',
                'verbose_name_plural': 'project set',
            },
            bases=(datagrowth.datatypes.documents.db.collection.DocumentCollectionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(default=dict)),
                ('identity', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('pending_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('inactive', 'In-active'), ('skipped', 'Skipped')], db_index=True, default='active', max_length=50)),
                ('metadata', models.JSONField(blank=True, db_index=True, decoder=core.utils.decoders.HarvesterJSONDecoder, default=core.models.datatypes.document.document_metadata_default, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tasks', models.JSONField(blank=True, default=projects.models.datatypes.project.default_document_tasks)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='projects.set')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.datasetversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.PositiveIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.batch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectdocument')),
                ('result_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_specification', models.CharField(db_index=True, help_text="The slug for the 'set' you want to harvest", max_length=255)),
                ('harvested_at', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.dataset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.harvestentity')),
                ('harvest_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.set')),
            ],
            options={
                'verbose_name': 'project harvest state',
                'verbose_name_plural': 'project harvest states',
            },
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='historic_sets',
            field=models.ManyToManyField(blank=True, to='projects.set'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search.opensearchindex'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='entities',
            field=models.ManyToManyField(related_name='+', through='projects.HarvestState', to='sources.harvestentity'),
        ),
        migrations.AddField(
            model_name='batch',
            name='documents',
            field=models.ManyToManyField(through='projects.ProcessResult', to='projects.projectdocument'),
        ),
    ]
