# Generated by Django 4.2.20 on 2025-04-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_publinova'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hkuprojectresource',
            options={'verbose_name': 'HKU project harvest', 'verbose_name_plural': 'HKU project harvests'},
        ),
        migrations.AlterModelOptions(
            name='huprojectresource',
            options={'verbose_name': 'HU project harvest', 'verbose_name_plural': 'HU project harvests'},
        ),
    ]
