# Generated by Django 4.2.16 on 2024-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestentity',
            name='type',
            field=models.CharField(choices=[('organizations', 'Organization'), ('products', 'Product'), ('files', 'File'), ('projects', 'Project'), ('testing', 'Test')], db_index=True, max_length=50),
        ),
    ]
