# Generated by Django 4.2.19 on 2025-03-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestentity',
            name='type',
            field=models.CharField(choices=[('organizations', 'Organization'), ('persons', 'Person'), ('products', 'Product'), ('files', 'File'), ('projects', 'Project'), ('testing', 'Test')], db_index=True, max_length=50),
        ),
    ]
