# Generated by Django 4.2.22 on 2025-06-17 09:07

from django.conf import settings
from django.db import migrations, models


def load_staging_providers_from_settings(apps, schema_editor):
    HarvestSource = apps.get_model("sources.HarvestSource")
    sharekit_source = HarvestSource.objects.filter(module="sharekit").last()
    if sharekit_source is not None:
        sharekit_source.staging_providers = settings.SHAREKIT_TEST_ORGANIZATIONS
        sharekit_source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestsource',
            name='staging_providers',
            field=models.JSONField(blank=True, default=list, help_text="List of names of providers from repository sources who's Documents should get state=skipped on production to prevent exposure, while allowing normal processing/display on other environments."),
        ),
        migrations.RunPython(load_staging_providers_from_settings, migrations.RunPython.noop),
    ]
