# Generated by Django 4.2.11 on 2024-05-13 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0013_anatomy_tool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edurepoaipmh',
            options={'verbose_name': 'Edurep OAIPMH harvest', 'verbose_name_plural': 'Edurep OAIPMH harvests'},
        ),
        migrations.AlterField(
            model_name='edurepoaipmh',
            name='retainer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
