# Generated by Django 4.2.13 on 2024-07-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0015_sharekit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hanoaipmhresource',
            name='retainer_type',
        ),
        migrations.DeleteModel(
            name='EdurepJsonSearchResource',
        ),
        migrations.DeleteModel(
            name='HanOAIPMHResource',
        ),
    ]
