# Generated by Django 4.2.13 on 2024-07-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sources', '0016_remove_han_edurep_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anatomytooloaipmh',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='anatomytooloaipmh',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='anatomytooloaipmh',
            name='since',
        ),
        migrations.RemoveField(
            model_name='buaspureresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='buaspureresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='buaspureresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='edurepoaipmh',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='edurepoaipmh',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='edurepoaipmh',
            name='since',
        ),
        migrations.RemoveField(
            model_name='greenioaipmhresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='greenioaipmhresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='greenioaipmhresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='hanzeresearchobjectresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='hanzeresearchobjectresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='hanzeresearchobjectresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='hkumetadataresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='hkumetadataresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='hkumetadataresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='hvapureresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='hvapureresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='hvapureresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='publinovametadataresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='publinovametadataresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='publinovametadataresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='saxionoaipmhresource',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='saxionoaipmhresource',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='saxionoaipmhresource',
            name='since',
        ),
        migrations.RemoveField(
            model_name='sharekitmetadataharvest',
            name='is_extracted',
        ),
        migrations.RemoveField(
            model_name='sharekitmetadataharvest',
            name='set_specification',
        ),
        migrations.RemoveField(
            model_name='sharekitmetadataharvest',
            name='since',
        ),
        migrations.AlterField(
            model_name='anatomytooloaipmh',
            name='retainer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
