from testing.tests.seeding.simple import TestSimpleHttpSeedingProcessor
from testing.tests.seeding.merge import TestMergeHttpSeedingProcessor
from testing.tests.seeding.nested import TestNestedHttpSeedingProcessor
