from testing.tests.seeding.simple import TestSimpleHttpSeedingProcessor, TestSimpleUpdateHttpSeedingProcessor
from testing.tests.seeding.merge import TestMergeHttpSeedingProcessor
from testing.tests.seeding.nested import TestNestedHttpSeedingProcessor, TestNestedDeletesHttpSeedingProcessor
