# Generated by Django 4.2.11 on 2024-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_new_harvester'),
        ('testing', '0003_test_client_mocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='entities',
            field=models.ManyToManyField(related_name='+', through='testing.HarvestState', to='sources.harvestentity'),
        ),
    ]
