# Generated by Django 4.2.11 on 2024-05-25 11:31

from django.db import migrations, models
import django.db.models.deletion
import testing.models.manual.file
import testing.models.manual.product


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_new_harvester'),
        ('testing', '0005_test_check_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_specification', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(default=testing.models.manual.product.product_properties_default)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.harvestentity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_specification', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('mime_type', models.CharField(choices=[('application/Inspire', 'application/Inspire'), ('application/msword', 'application/msword'), ('application/octet-stream', 'application/octet-stream'), ('application/pdf', 'application/pdf'), ('application/postscript', 'application/postscript'), ('application/powerpoint', 'application/powerpoint'), ('application/ppt', 'application/ppt'), ('application/rtf', 'application/rtf'), ('application/vnd.google-earth.kmz', 'application/vnd.google-earth.kmz'), ('application/vnd.koan', 'application/vnd.koan'), ('application/vnd.ms-excel', 'application/vnd.ms-excel'), ('application/vnd.ms-powerpoint', 'application/vnd.ms-powerpoint'), ('application/vnd.ms-powerpoint.presentation.macroEnabled.12', 'application/vnd.ms-powerpoint.presentation.macroEnabled.12'), ('application/vnd.ms-publisher', 'application/vnd.ms-publisher'), ('application/vnd.ms-word', 'application/vnd.ms-word'), ('application/vnd.ms-word.document.macroEnabled.12', 'application/vnd.ms-word.document.macroEnabled.12'), ('application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.spreadsheet'), ('application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'), ('application/vnd.openxmlformats-officedocument.presentationml.slideshow', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'), ('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'), ('application/vnd.openxmlformats-officedocument.wordprocessingml.template', 'application/vnd.openxmlformats-officedocument.wordprocessingml.template'), ('application/x-ACTIVprimary3', 'application/x-ACTIVprimary3'), ('application/x-AS3PE', 'application/x-AS3PE'), ('application/x-Inspire', 'application/x-Inspire'), ('application/x-Wikiwijs-Arrangement', 'application/x-Wikiwijs-Arrangement'), ('application/x-ibooks+zip', 'application/x-ibooks+zip'), ('application/x-java', 'application/x-java'), ('application/x-koan', 'application/x-koan'), ('application/x-mplayer2', 'application/x-mplayer2'), ('application/x-pdf', 'application/x-pdf'), ('application/x-rar-compressed', 'application/x-rar-compressed'), ('application/x-smarttech-notebook', 'application/x-smarttech-notebook'), ('application/x-stuffit', 'application/x-stuffit'), ('application/x-tar', 'application/x-tar'), ('application/x-yossymemo', 'application/x-yossymemo'), ('application/x-zip', 'application/x-zip'), ('application/x-zip-compressed', 'application/x-zip-compressed'), ('application/xhtml+xml', 'application/xhtml+xml'), ('application/zip', 'application/zip'), ('audio/midi', 'audio/midi'), ('audio/mpeg', 'audio/mpeg'), ('audio/x-wav', 'audio/x-wav'), ('image', 'image'), ('image/bmp', 'image/bmp'), ('image/gif', 'image/gif'), ('image/jpeg', 'image/jpeg'), ('image/jpg', 'image/jpg'), ('image/pjpeg', 'image/pjpeg'), ('image/png', 'image/png'), ('image/tiff', 'image/tiff'), ('image/x-icon', 'image/x-icon'), ('image/x-ms-bmp', 'image/x-ms-bmp'), ('message/rfc822', 'message/rfc822'), ('text/html', 'text/html'), ('text/plain', 'text/plain'), ('text/rtf', 'text/rtf'), ('text/xml', 'text/xml'), ('unknown', 'unknown'), ('video', 'video'), ('video/flv', 'video/flv'), ('video/mp4', 'video/mp4'), ('video/mpeg', 'video/mpeg'), ('video/quicktime', 'video/quicktime'), ('video/vnd.youtube.yt', 'video/vnd.youtube.yt'), ('video/x-flv', 'video/x-flv'), ('video/x-ms-asf', 'video/x-ms-asf'), ('video/x-ms-wmv', 'video/x-ms-wmv'), ('video/x-msvideo', 'video/x-msvideo')], default='unknown')),
                ('properties', models.JSONField(default=testing.models.manual.file.file_properties_default)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.harvestentity')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.testproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
