# Generated by Django 4.2.20 on 2025-04-24 09:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_improve_document_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='overwrite',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.datasetversion'),
        ),
        migrations.AddField(
            model_name='overwrite',
            name='derivatives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='overwrite',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overwrite',
            name='pending_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='overwrite',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='overwrite',
            name='tasks',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='set',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='testdocument',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
