# Generated by Django 4.2.13 on 2024-07-10 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharekit', '0003_is_extracted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharekitMetadataHarvest',
        ),
    ]
