# Settings related to network and clusters
network:
  host: 0.0.0.0
cluster:
  name: "opensearch"
discovery:
  type: "single-node"


# Settings related to individual nodes
node:
  name: "opensearch"
bootstrap:
  memory_lock: true
path:
  repo: ["/usr/share/opensearch/repositories"]

plugins.security.disabled: true
plugins.security.ssl.http.enabled: false
