# Generated by Django 4.2.13 on 2024-07-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensearchindex',
            name='entity',
            field=models.CharField(default='products', max_length=50),
        ),
    ]
