# Generated by Django 4.2.14 on 2024-08-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensearchindex',
            name='entity',
            field=models.CharField(default='products', max_length=50),
        ),
        migrations.AlterField(
            model_name='opensearchindex',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
