# Generated by Django 4.2.20 on 2025-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_multi_entity_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='opensearchindex',
            name='opened_at',
            field=models.DateTimeField(blank=True, help_text='Indicates when the index was opened for indexing. Set to None to close the index.', null=True),
        ),
    ]
