# Generated by Django 3.2.20 on 2023-09-11 12:30

import core.models.datatypes.dataset
import core.models.datatypes.document
import core.models.datatypes.set
import core.utils.decoders
import datagrowth.configuration.fields
import datagrowth.datatypes.documents.db.collection
import datetime
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import files.models.datatypes.file
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0011_harvest_sources'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_harvested', models.BooleanField(default=False)),
                ('indexing', models.CharField(choices=[('no', 'No'), ('index_only', 'Index only'), ('index_and_promote', 'Index and promote')], default='no', max_length=50)),
            ],
            options={
                'verbose_name': 'file dataset',
                'verbose_name_plural': 'file datasets',
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('pending_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(blank=True, default=core.models.datatypes.dataset.version_default, max_length=50)),
                ('tasks', models.JSONField(blank=True, default=core.models.datatypes.dataset.default_dataset_version_tasks)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.dataset')),
            ],
            options={
                'verbose_name': 'file dataset version',
                'verbose_name_plural': 'file dataset version',
            },
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('properties', models.JSONField(default=dict)),
                ('identity', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('pending_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('inactive', 'In-active'), ('skipped', 'Skipped')], db_index=True, default='active', max_length=50)),
                ('metadata', models.JSONField(blank=True, decoder=core.utils.decoders.HarvesterJSONDecoder, default=core.models.datatypes.document.document_metadata_default, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tasks', models.JSONField(blank=True, default=files.models.datatypes.file.default_document_tasks)),
                ('domain', models.CharField(blank=True, max_length=256, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(choices=[('app', 'App'), ('audio', 'Audio'), ('document', 'Document'), ('image', 'Image'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('unknown', 'Unknown'), ('video', 'Video'), ('website', 'Website')], default='unknown', max_length=50)),
                ('is_not_found', models.BooleanField(default=False)),
                ('is_analysis_allowed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeThumbnailResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('command', models.JSONField(blank=True, default=None, null=True)),
                ('stdin', models.TextField(blank=True, default=None, null=True)),
                ('stdout', models.TextField(blank=True, default=None, null=True)),
                ('stderr', models.TextField(blank=True, default=None, null=True)),
                ('preview', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='files/previews/youtube')),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('derivatives', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delete_policy', models.CharField(blank=True, choices=[('no', 'No'), ('persistent', 'Persistent'), ('transient', 'Transient')], max_length=50, null=True)),
                ('tasks', models.JSONField(blank=True, default=core.models.datatypes.set.default_set_tasks)),
                ('pending_at', models.DateTimeField(blank=True, null=True)),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='files.datasetversion')),
            ],
            options={
                'verbose_name': 'file set',
                'verbose_name_plural': 'file set',
            },
            bases=(datagrowth.datatypes.documents.db.collection.DocumentCollectionMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.PositiveIntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.batch')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filedocument')),
                ('result_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PdfThumbnailResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request', models.JSONField(blank=True, default=None, null=True)),
                ('head', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('preview', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='files/previews/pdf')),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Overwrite',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('identity', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('properties', models.JSONField(default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.set')),
            ],
            options={
                'verbose_name': 'file overwrite',
                'verbose_name_plural': 'file overwrites',
            },
        ),
        migrations.CreateModel(
            name='HttpTikaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request', models.JSONField(blank=True, default=None, null=True)),
                ('head', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_specification', models.CharField(db_index=True, help_text="The slug for the 'set' you want to harvest", max_length=255)),
                ('harvested_at', models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc))),
                ('purge_after', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.dataset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sources.harvestentity')),
                ('harvest_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.set')),
            ],
            options={
                'verbose_name': 'file harvest state',
                'verbose_name_plural': 'file harvest states',
            },
        ),
        migrations.AddField(
            model_name='filedocument',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_set', to='files.set'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='files.datasetversion'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='overwrite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.overwrite'),
        ),
        migrations.CreateModel(
            name='ExtructResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request', models.JSONField(blank=True, default=None, null=True)),
                ('head', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='historic_sets',
            field=models.ManyToManyField(blank=True, to='files.Set'),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search.opensearchindex'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='entities',
            field=models.ManyToManyField(related_name='_files_dataset_entities_+', through='files.HarvestState', to='sources.HarvestEntity'),
        ),
        migrations.AddField(
            model_name='batch',
            name='documents',
            field=models.ManyToManyField(through='files.ProcessResult', to='files.FileDocument'),
        ),
    ]
