# Generated by Django 3.2.20 on 2023-10-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
