# Generated by Django 3.2.20 on 2023-10-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_finished_at'),
        ('files', '0002_youtube_api_resource'),
    ]

    operations = [
    ]
