# Generated by Django 4.2.13 on 2024-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_proper_files_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedocument',
            name='is_analysis_allowed',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='is_not_found',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='mime_type',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='redirects',
            field=models.CharField(choices=[('exclusive_permanent', 'Exclusively permanent redirects'), ('temporary', 'At least one temporary redirect'), ('no', 'No redirects')], db_index=True, default='no', max_length=50),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='type',
            field=models.CharField(choices=[('app', 'App'), ('audio', 'Audio'), ('document', 'Document'), ('image', 'Image'), ('presentation', 'Presentation'), ('spreadsheet', 'Spreadsheet'), ('unknown', 'Unknown'), ('video', 'Video'), ('website', 'Website')], db_index=True, default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
