# Generated by Django 4.2.20 on 2025-05-13 11:30

import datagrowth.configuration.fields
from django.db import migrations, models, connection
import django.db.models.deletion
import versatileimagefield.fields


def rename_with_inheritance(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS files_youtubethumbnailresource_uri_2b595bc1;")
        cursor.execute("DROP INDEX IF EXISTS files_youtubethumbnailresource_uri_2b595bc1_like;")
        cursor.execute("DROP INDEX IF EXISTS files_youtubethumbnailresource_retainer_type_id_0806f661;")


def reverse_rename(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0012_dataset_version_storage'),
    ]

    operations = [
        migrations.RunPython(rename_with_inheritance, reverse_rename),
        migrations.RenameModel(
            old_name='YoutubeTranscriptsResource',
            new_name='VideoTranscriptsResource',
        ),
        migrations.RenameModel(
            old_name='YoutubeThumbnailResource',
            new_name='VideoThumbnailResource',
        ),
        migrations.AlterField(
            model_name='videothumbnailresource',
            name='preview',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True,
                                                                 upload_to='files/previews/video'),
        ),
        migrations.CreateModel(
            name='YoutubeThumbnailResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(db_index=True, default=None, max_length=255)),
                ('status', models.PositiveIntegerField(default=0)),
                ('config', datagrowth.configuration.fields.ConfigurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purge_at', models.DateTimeField(blank=True, null=True)),
                ('retainer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_hash', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('request', models.JSONField(blank=True, default=None, null=True)),
                ('head', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('preview', versatileimagefield.fields.VersatileImageField(blank=True, null=True,
                                                                           upload_to='files/previews/youtube')),
                ('retainer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                    to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
