# Generated by Django 4.2.20 on 2025-05-13 11:30

import datagrowth.configuration.fields
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('files', '0012_dataset_version_storage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeTranscriptsResource',
            new_name='VideoTranscriptsResource',
        ),
        migrations.RenameModel(
            old_name='YoutubeThumbnailResource',
            new_name='VideoThumbnailResource',
        ),
        migrations.AlterField(
            model_name='videothumbnailresource',
            name='preview',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True,
                                                                 upload_to='files/previews/video'),
        ),
    ]
