# Generated by Django 4.2.16 on 2024-10-30 16:42

from django.conf import settings
from django.db import migrations

from metadata.utils.operations import get_or_create_metadata_field


def add_projects_metadata_fields(apps, schema_editor):
    MetadataField = apps.get_model('metadata', 'MetadataField')
    if not MetadataField.objects.exists():
        return
    MetadataField.objects.filter(name__in=["modified_at", "published_at"]).delete()
    if settings.PLATFORM.value == "publinova":
        get_or_create_metadata_field("provider", "projects:default", "Instelling", "Institute")
        get_or_create_metadata_field("provider", "products:default", "Instelling", "Institute")
        get_or_create_metadata_field(
            "project_status", "projects:default", "Project status", "Project status"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_skos_sources'),
    ]

    operations = [
        migrations.RunPython(
            add_projects_metadata_fields,
            migrations.RunPython.noop,
        )
    ]
