# Generated by Django 4.2.16 on 2024-11-05 11:24

from django.core.management import call_command
from django.db import migrations
from django.utils.timezone import now
from pydantic import UUID4

from metadata.models import MetadataField, MetadataValue, SkosMetadataSource


BEGRIPPENKADER_PREFIX = "http://purl.edustandaard.nl/begrippenkader/"


def transform_discipline_values_to_skos(apps, schema_editor):
    metadata_values_queryset = MetadataValue.objects.filter(field__name="disciplines", field__is_manual=False)
    if not metadata_values_queryset.exists():
        return

    # Delete all currently deleted metadata values
    metadata_values_queryset.filter(deleted_at__isnull=False).delete()

    # Deal with existing values
    for metadata_value in metadata_values_queryset.iterator():
        # Any value with a UUID as name has never been properly translated
        # We'll delete those values and load them in again through SKOS
        try:
            UUID4(metadata_value.name)
            metadata_value.deleted_at = now()
            metadata_value.save()
        except ValueError:
            pass
        try:
            UUID4(metadata_value.value)
            # Here we are assuming that all UUID raw values are actually "begrippenkader" terms.
            # So we set that prefix and preserve tree order for these MetadataValues.
            metadata_value.value = f"{BEGRIPPENKADER_PREFIX}{metadata_value.value}"
            metadata_value.save()
        except ValueError:
            # Any values that have a non-UUID raw value are fine and will be skipped
            pass

    # Delete all newly deleted MetadataValues
    metadata_values_queryset.filter(deleted_at__isnull=False).delete()

    # Load SKOS values
    skos_discipline_source = "Disciplines (NL-LOM)"
    disciplines_field = MetadataField.objects.get(name="disciplines")
    source, created = SkosMetadataSource.objects.get_or_create(
        name=skos_discipline_source,
        defaults={
            "skos_url": "https://vocabulaires.edurep.nl/sector/mbo/mbo_opleidingsdomeinen_en_studierichtingen/mbo_opleidingsdomeinen_en_studierichtingen-2015.01.skos.json",
            "target_field": disciplines_field,
            "parent_value": None
        }
    )
    if created:
        # Load the SKOS values which will be manual by default
        call_command("harvest_skos_sources", "--source", skos_discipline_source)
        # Mark the manual values as hidden instead
        MetadataValue.objects.filter(field__name="disciplines", is_manual=True).update(is_manual=False, is_hidden=True)

    # Remove all normalized values that were never really normalized
    MetadataValue.objects.filter(field__name="disciplines_normalized.keyword", is_hidden=True).delete()
    MetadataValue.objects.filter(field__name="learning_material_disciplines_normalized", is_hidden=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_projects'),
    ]

    operations = [
        migrations.RunPython(
            transform_discipline_values_to_skos,
            migrations.RunPython.noop,
        )
    ]
