# Generated by Django 4.2.20 on 2025-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatafield',
            name='entity',
            field=models.CharField(choices=[('organizations', 'organizations'), ('organizations:default', 'organizations:default'), ('persons', 'persons'), ('persons:default', 'persons:default'), ('products', 'products'), ('products:default', 'products:default'), ('products:multilingual-indices', 'products:multilingual-indices'), ('projects', 'projects'), ('projects:default', 'projects:default')], default='products', help_text='Indicates which entity and/or search configuration controls metadata for this field.', max_length=100),
        ),
    ]
