# Generated by Django 3.2.23 on 2024-02-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_studyvocabularyresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafield',
            name='value_output_order',
            field=models.CharField(choices=[('frequency', 'Frequency'), ('alphabetical', 'Alphabetical'), ('manual', 'Manual')], default='frequency', max_length=50),
        ),
    ]
