# Generated by Django 4.2.14 on 2024-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_value_output_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatafield',
            name='entity',
            field=models.CharField(choices=[('products', 'products'), ('products:default', 'products:default'), ('products:multilingual-indices', 'products:multilingual-indices'), ('projects', 'projects'), ('projects:default', 'projects:default')], default='products', help_text='Indicates which entity and/or search configuration controls metadata for this field.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='metadatavalue',
            unique_together={('field', 'value')},
        ),
        migrations.RemoveField(
            model_name='metadatavalue',
            name='site',
        )
    ]
