# Generated by Django 4.2.20 on 2025-04-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_publinova'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='persondocument',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='set',
            name='task_results',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
