# Generated by Django 4.2.11 on 2024-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0013_anatomy_tool'),
        ('products', '0002_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='entities',
            field=models.ManyToManyField(related_name='+', through='products.HarvestState', to='sources.harvestentity'),
        ),
    ]
