# Generated by Django 4.2.13 on 2024-07-08 14:53

import core.models.datatypes.document
import core.utils.decoders
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_django_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='metadata',
            field=models.JSONField(blank=True, db_index=True, decoder=core.utils.decoders.HarvesterJSONDecoder, default=core.models.datatypes.document.document_metadata_default, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
