name: Harvester CI

on:
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: qwerty
          POSTGRES_DB: edushare
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: sudo apt-get install python3-dev libpq-dev gettext
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        APPLICATION_CONTEXT: host
        APPLICATION_MODE: localhost
        POL_POSTGRES_HOST: 127.0.0.1
      run:
        invoke test.harvester
